### PR TITLE
Close #16

### LINKED ISSUE #16: Text of comments is cut
Some code comments are cut and the text is not full in the model.
E.g.:
Parsing of (always in the https://github.com/awillemant/puho git repo):

```
class FrancePublicHolidayService {
   List<LocalDate> getPublicHolidaysByYear(final int year) {
    ....
    }


    //thanks to http://www.aveol.fr/?p=602
    private LocalDate getLundiPaques(final int year) {

    }

}
```

Give a comment with only // instead of //thanks to http://www.aveol.fr/?p=602

### PR DESCRIPTION
**Pull request by VincentBlondeau**
This should solve the problem of comments

### CODE REVIEW

**Comment by girba** [comment]
Thanks. I took a quick look:
- commit 6811078 introduces a new formatting of code. The previous formatting was intentional, I would prefer to keep it like that. As it is I could not identify where the fix for issue #16 actually is.
- I would want a different design for the options that does not involve so many ifs. That needs to be reworked.

Would you like to give it another try?

**Comment by girba** [comment]
The code that I use for exporting FAMIX is:

    tower := MoosePragmaProcessor new 
        rejectedPackageNames: #(Dynamix Dude Hismo);
        queue: FAMIXEntity withAllSubclasses;
        run;
        asTower.
     'famix30.fm3.mse' asFileReference writeStreamDo: [ :s |
        tower metamodel exportOn: s ]

**Comment by VincentBlondeau** [comment]
I don't understand yet how the pull request works because I wanted to push only the first commit and not the other that are not related at all with the first issue....
I will discover it soonly

**Comment by VincentBlondeau** [comment]
I will do another cleaner pull request.

**Pull request closed without merging**
